studyoverflow/posts/urls.py
from django.urls import path
from posts import views


app_name = "posts"


urlpatterns = [
    path("", views.PostListView.as_view(), name="list"),
    path("create/", views.PostCreateView.as_view(), name="create"),
    path("<int:pk>/<slug:slug>/", views.PostDetailView.as_view(), name="detail"),
    path("edit/<int:pk>/<slug:slug>/", views.PostUpdateView.as_view(), name="edit"),
    path("delete/<int:pk>/<slug:slug>/", views.PostDeleteView.as_view(), name="delete"),
    path(
        "<int:post_pk>/<slug:post_slug>/comments/",
        views.CommentListView.as_view(),
        name="comment_list",
    ),
    path(
        "<int:post_pk>/<slug:post_slug>/comments/root/create/",
        views.CommentRootCreateView.as_view(),
        name="comment_root_create",
    ),
    path(
        "<int:post_pk>/<slug:post_slug>/comments/child/create/",
        views.CommentChildCreateView.as_view(),
        name="comment_child_create",
    ),
    path(
        "<int:post_pk>/<slug:post_slug>/comments/<int:comment_pk>/update/",
        views.CommentUpdateView.as_view(),
        name="comment_update",
    ),
    path(
        "<int:post_pk>/<slug:post_slug>/comments/<int:comment_pk>/delete/",
        views.CommentDeleteView.as_view(),
        name="comment_delete",
    ),
    path(
        "<int:post_pk>/<slug:post_slug>/likes/",
        views.ToggleLikePostView.as_view(),
        name="toggle_like_post",
    ),
    path(
        "<int:post_pk>/<slug:post_slug>/comments/<int:comment_pk>/likes/",
        views.ToggleLikeCommentView.as_view(),
        name="toggle_like_comment",
    ),
]

studyoverflow/users/urls.py
from django.urls import path
from users import views


app_name = "users"


urlpatterns = [
    path("", views.UsersListView.as_view(), name="list"),
    path("list-htmx/", views.UsersListHTMXView.as_view(), name="list_htmx"),
    path("register/", views.UserRegisterView.as_view(), name="register"),
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("logout/", views.UserLogoutView.as_view(), name="logout"),
    path("delete/", views.UserDeleteView.as_view(), name="delete"),
    path("profile/me/", views.UserProfileUpdateView.as_view(), name="my_profile"),
    path("profile/<slug:username>/", views.AuthorProfileView.as_view(), name="profile"),
    path("avatar/<slug:username>/preview/", views.avatar_preview, name="avatar_preview"),
    path("password-change/", views.UserPasswordChangeView.as_view(), name="password_change"),
    path("password-reset/", views.UserPasswordResetView.as_view(), name="password_reset"),
    path(
        "password-reset/done/",
        views.UserPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password-reset/confirm/<uidb64>/<token>/",
        views.UserPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        views.UserPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("block/<int:user_id>/", views.block_user, name="block_user"),
    path("unblock/<int:user_id>/", views.unblock_user, name="unblock_user"),
]

studyoverflow/posts/views.py
import json
import logging
from abc import ABC, abstractmethod
from typing import Type

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.cache import cache
from django.db import models
from django.db.models import Count, Prefetch
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView
from posts.forms import CommentCreateForm, CommentUpdateForm, PostCreateForm, PostFilterForm
from posts.models import Comment, Post
from posts.services.infrastructure import (
    CommentGetMethodMixin,
    CommentSortMixin,
    ContextTagMixin,
    HTMXHandle404CommentMixin,
    HTMXMessageMixin,
    LikeAnnotationsMixin,
    LoginRequiredHTMXMixin,
    PostAnnotateQuerysetMixin,
    PostAuthorMixin,
    PostFilterSortMixin,
    SingleObjectCacheMixin,
)
from users.services.infrastructure import IsAuthorOrModeratorMixin


logger = logging.getLogger(__name__)


# ----------------------------------------
# Post Views
# ----------------------------------------


class PostListView(ContextTagMixin, PostFilterSortMixin, PostAnnotateQuerysetMixin, ListView):
    """
    Страница со списком постов с тегами, аннотациями, фильтрацией и сортировкой.

    Использует:
    - ContextTagMixin: для добавления тегов в контекст.
    - PostAnnotateQuerysetMixin: select_related, prefetch_related и аннотации.
    - PostFilterSortMixin: фильтрация и сортировка.
    """

    model = Post
    template_name = "posts/post_list.html"
    context_object_name = "posts"
    paginate_by = 7
    extra_context = {"section_of_menu_selected": "posts:list"}

    def get_queryset(self):
        queryset = super().get_queryset()

        # Фильтрация по полям модели (через PostFilterSortMixin)
        queryset = self.filter_by_model_fields(queryset, self.request)

        # select_related, prefetch_related и аннотации (через PostAnnotateQuerysetMixin)
        queryset = self.get_annotate_queryset(queryset)

        # Фильтрация и сортировка по аннотированным полям (через PostFilterSortMixin)
        queryset = self.filter_and_sort_by_annotations(queryset, self.request)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        filter_form = PostFilterForm(self.request.GET or None)

        if filter_form.data.get("author"):
            filter_form.is_valid()

        context["filter_form"] = filter_form

        get_params = self.request.GET.copy()
        if "page" in get_params:
            get_params.pop("page")
        context["querystring"] = get_params.urlencode()

        return context


class PostCreateView(PostAuthorMixin, LoginRequiredHTMXMixin, SuccessMessageMixin, CreateView):
    """
    Страница создания нового поста.

    Логирует создание поста и добавляет сообщение об успешном создании.
    """

    form_class = PostCreateForm
    template_name = "posts/post_create.html"
    success_url = reverse_lazy("posts:list")
    success_message = "Пост успешно создан!"

    def get_context_data(self, **kwargs):
        """Добавляет выбранный раздел меню в контекст."""
        context = super().get_context_data(**kwargs)
        context["section_of_menu_selected"] = "posts:create"
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        post = self.object
        logger.info(
            f"Пост создан: {post.title} (id: {post.id}).",
            extra={
                "post_id": post.id,
                "author_id": self.request.user.id,
                "event_type": "post_create",
            },
        )
        return response


class PostDetailView(PostAnnotateQuerysetMixin, DetailView):
    """
    Страница просмотра подробностей поста с кешированием его данных.
    """

    model = Post
    template_name = "posts/post_detail.html"
    context_object_name = "post"

    def get_object(self, queryset=None):
        """Возвращает объект поста с кешированием."""
        post_id = self.kwargs.get(self.pk_url_kwarg)
        user_id = self.request.user.id if self.request.user.is_authenticated else "anon"
        cache_key = f"post_detail_{post_id}_u{user_id}"

        obj = cache.get(cache_key)
        if not obj:
            obj = super().get_object(queryset)
            # кеш 2 сек, чтобы данные быстро обновлялись для наглядности
            cache.set(cache_key, obj, 2)
        return obj

    def get_queryset(self):
        queryset = super().get_queryset()

        # select_related, prefetch_related и аннотации (через PostAnnotateQuerysetMixin)
        return super().get_annotate_queryset(queryset)

    def get_context_data(self, **kwargs):
        """Добавляет пустую форму для создания комментария в контекст."""
        context = super().get_context_data(**kwargs)
        # Пустая форма в шаблон для написания комментария
        context["comment_form"] = CommentCreateForm()
        return context


class PostUpdateView(
    LoginRequiredMixin,
    IsAuthorOrModeratorMixin,
    SingleObjectCacheMixin,
    SuccessMessageMixin,
    UpdateView,
):
    """
    Страница редактирования поста.

    Логирует изменения и проверяет права пользователя.
    """

    model = Post
    form_class = PostCreateForm
    template_name = "posts/post_edit.html"
    context_object_name = "post"
    permission_required = "posts.moderate_post"
    success_message = "Пост успешно изменен!"

    def get_queryset(self):
        return super().get_queryset().select_related("author").prefetch_related("tags")

    def form_valid(self, form):
        response = super().form_valid(form)
        post = self.object
        logger.info(
            f"Пост отредактирован: {post.title} (id: {post.id}).",
            extra={
                "post_id": post.id,
                "editor_id": self.request.user.id,
                "event_type": "post_update",
            },
        )
        return response


class PostDeleteView(
    LoginRequiredMixin, IsAuthorOrModeratorMixin, SingleObjectCacheMixin, DeleteView
):
    """
    Удаление поста.

    Логирует удаление и показывает сообщение пользователю.
    """

    model = Post
    success_url = reverse_lazy("posts:list")
    permission_required = "posts.moderate_post"

    def form_valid(self, form):
        post = self.get_object()
        logger.info(
            f"Пост удален: {post.title} (id: {post.id}).",
            extra={
                "post_id": post.id,
                "deleter_id": self.request.user.id,
                "event_type": "post_delete",
            },
        )

        messages.info(self.request, "Пост удален.")
        return super().form_valid(form)


# ----------------------------------------
# Comment Views
# ----------------------------------------


class CommentListView(LikeAnnotationsMixin, CommentSortMixin, ListView):
    """
    Страница со списком комментариев к посту с аннотациями и сортировкой.
    """

    model = Comment
    template_name = "posts/comments/comment_list.html"
    context_object_name = "root_comments"

    def _get_post_object(self):
        """
        Возвращает кешированный объект поста, к которому относятся комментарии.
        """
        if not hasattr(self, "_post_object"):
            post_pk = self.kwargs.get("post_pk")
            self._post_object = get_object_or_404(
                Post.objects.annotate(comments_count=Count("comments")), pk=post_pk
            )
        return self._post_object

    def get_queryset(self):
        """
        Возвращает queryset родительских комментариев с
        prefetch_related queryset дочерних комментариев.

        Используются select_related для оптимизации запроса и аннотации.
        """
        post = self._get_post_object()

        child_queryset = self.annotate_queryset(
            Comment.objects.select_related(
                "author", "post", "reply_to", "reply_to__author"
            ).order_by("-time_create")
        )

        queryset = (
            post.comments.roots()
            .select_related("author", "post")
            # prefetch_related для обратного доступа ForeignKey через related_name
            .prefetch_related(Prefetch("child_comments", queryset=child_queryset))
            .order_by("-time_create")
        )

        queryset = self.annotate_queryset(queryset)

        queryset = self.sort_comments(queryset)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self._get_post_object()
        context["post"] = post
        context["comment_form"] = CommentCreateForm()
        return context


class CommentRootCreateView(
    LoginRequiredHTMXMixin, HTMXMessageMixin, CommentGetMethodMixin, CreateView
):
    """
    Создание родительского комментария к посту.

    Работает с HTMX для создания комментария и обновления списка комментариев
    без перезагрузки страницы.
    Логирует создание комментария.
    """

    model = Comment
    form_class = CommentCreateForm
    template_name = "posts/comments/_comment_root_form.html"

    def get_form_kwargs(self):
        """
        Добавляет в kwargs пользователя и пост, к которому пишется комментарий.
        """
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        if not hasattr(self, "_cached_post"):
            self._cached_post = get_object_or_404(Post, id=self.kwargs.get("post_pk"))
        kwargs["post"] = self._cached_post
        return kwargs

    def get_context_data(self, form, form_valid=True, **kwargs):
        context = super().get_context_data(**kwargs)
        context.pop("form")
        reply_to = form.cleaned_data.get("reply_to")
        context = {
            "post": form.post,

studyoverflow/posts/views/like_views.py
import json
import logging
from abc import ABC, abstractmethod
from typing import Type

from django.contrib import messages
from django.db import models
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from posts.models import Comment, Post

from .mixins import HTMXMessageMixin, LoginRequiredHTMXMixin


logger = logging.getLogger(__name__)


class ToggleLikeBaseView(LoginRequiredHTMXMixin, HTMXMessageMixin, View, ABC):
    """
    Абстрактное базовое представление для добавления/удаления лайков.

    Работает с HTMX и логирует действия с лайками.
    """

    model: Type[models.Model]
    pk_url_kwarg: str = "pk"

    @abstractmethod
    def _get_toggle_like_url(self, liked_object: models.Model) -> str:
        """
        Должен возвращать URL для кнопки лайка.

        Нужно переопределять в дочерних классах."""
        pass

    def post(self, request, *args, **kwargs):
        """
        Добавляет или удаляет лайк для объекта.

        Возвращает HTMX-ответ с количеством лайков или триггером с перезагрузкой страницы
        в случае отсутствия объекта (DoesNotExist).
        """
        try:
            liked_object = self.model.objects.get(pk=kwargs[self.pk_url_kwarg])
        except self.model.DoesNotExist:
            response = HttpResponse(status=404)
            response["HX-Trigger"] = json.dumps({"reloadPage": True})

            messages.error(self.request, "Ресурс был удален.")

            return response

        like, created = liked_object.likes.get_or_create(user=request.user)

        if not created:
            like.delete()
            message_text = "Лайк удален."
            message_type = "info"
        else:
            message_text = "Лайк добавлен."
            message_type = "success"

        event_type = "like_add" if created else "like_remove"

        logger.info(
            f"Лайк {event_type} для {self.model.__name__} (id: {liked_object.pk}).",
            extra={
                "object_type": self.model.__name__.lower(),
                "object_id": liked_object.pk,
                "user_id": request.user.pk,
                "event_type": event_type,
            },
        )

        context = {
            "toggle_like_url": self._get_toggle_like_url(liked_object),
            "liked_object": liked_object,
            "likes_count": liked_object.likes.count(),
            "user_has_liked": created,
        }

        response = render(request, "posts/likes/_like-button.html", context)

        response = self.add_htmx_message_to_response(
            message_text=message_text, message_type=message_type, response=response
        )

        return response


class ToggleLikePostView(ToggleLikeBaseView):
    """
    Лайк / удаление лайка для поста.
    """

    model = Post
    pk_url_kwarg = "post_pk"

    def _get_toggle_like_url(self, post):
        """Возвращает URL для кнопки лайка поста."""
        return reverse_lazy(
            "posts:toggle_like_post", kwargs={"post_pk": post.pk, "post_slug": post.slug}
        )


class ToggleLikeCommentView(ToggleLikeBaseView):
    """
    Лайк / удаление лайка для комментария.
    """

    model = Comment
    pk_url_kwarg = "comment_pk"

    def _get_toggle_like_url(self, comment):
        """Возвращает URL для кнопки лайка комментария."""
        return reverse_lazy(
            "posts:toggle_like_comment",
            kwargs={
                "post_pk": comment.post.pk,
                "post_slug": comment.post.slug,
                "comment_pk": comment.pk,
            },
        )

studyoverflow/posts/templates/posts/_pagination.html
{# Пагинация #}
{% if page_obj.has_other_pages %}
  <nav>
    <ul class="pagination mb-4">

      <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
        <a class="page-link" href="?{{ querystring }}&page={{ page_obj.number|add:-1 }}">
          <span aria-hidden="true">«</span>
        </a>
      </li>

      {% if page_obj.number|add:-3 > 0 %}
        <li class="page-item">
          <a class="page-link" href="?{{ querystring }}&page={{ 1 }}">1</a>
        </li>

        <li class="page-item">
          <a class="page-link">...</a>
        </li>
      {% endif %}

      {% if page_obj.number|add:-2 > 0 %}
        <li class="page-item">
          <a class="page-link" href="?{{ querystring }}&page={{ page_obj.number|add:-2 }}">{{ page_obj.number|add:-2 }}</a>
        </li>
      {% endif %}

      {% if page_obj.number|add:-1 > 0 %}
        <li class="page-item">
          <a class="page-link" href="?{{ querystring }}&page={{ page_obj.number|add:-1 }}">{{ page_obj.number|add:-1 }}</a>
        </li>
      {% endif %}

      <li class="page-item active">
        <a class="page-link" href="#">{{ page_obj.number }}</a>
      </li>

      {% if page_obj.number|add:1 <= page_obj.paginator.num_pages %}
        <li class="page-item">
          <a class="page-link" href="?{{ querystring }}&page={{ page_obj.number|add:1 }}">{{ page_obj.number|add:1 }}</a>
        </li>
      {% endif %}

      {% if page_obj.number|add:2 <= page_obj.paginator.num_pages %}
        <li class="page-item">
          <a class="page-link" href="?{{ querystring }}&page={{ page_obj.number|add:2 }}">{{ page_obj.number|add:2 }}</a>
        </li>
      {% endif %}

      {% if page_obj.number|add:3 <= page_obj.paginator.num_pages %}
        <li class="page-item">
          <a class="page-link">...</a>
        </li>

        <li class="page-item">
          <a class="page-link" href="?{{ querystring }}&page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
        </li>
      {% endif %}

      <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
        <a class="page-link" href="?{{ querystring }}&page={{ page_obj.number|add:1 }}">
          <span aria-hidden="true">»</span>
        </a>
      </li>

    </ul>
  </nav>
{% endif %}

studyoverflow/posts/templates/posts/post_card.html
{% load posts_tags %}
{% load users_tags %}


{# Шаблон карточки поста #}
<div class="card text-white rounded shadow-sm px-4">
  <div class="card-body px-0 pb-2">

    {# Автор и время публикации #}
    <div class="d-flex align-items-center mb-2">

    <img id="avatar"
         src="{{ post.author.avatar_small_size1_url }}"
         alt="{{ post.author.username }}"
         class="rounded-circle"
         style="cursor:pointer;"

         hx-get="{% url 'users:avatar_preview' post.author.username %}"
         hx-target="#modal-image-container"
         hx-swap="innerHTML"

         hx-indicator="#modal-loading-indicator"
         hx-on:htmx:before-request="openModal()">

      <div class="image-modal-wrapper"></div>

      <div>
        <a id="username" href="{% url 'users:profile' post.author.username %}" class="author-name d-inline-block mb-1">
          {{ post.author.username }} {% user_role_badge post.author %}
        </a>

        <div id="time_create-time_update" class="text-secondary">
          Опубликовано: {{ post.time_create|date:"d.m.Y г. H:i" }}
          {% if post.is_edited %}
            &nbsp;|&nbsp; Изменено: {{ post.time_update|date:"d.m.Y г. H:i" }}
          {% endif %}
        </div>
      </div>

    </div>

    <hr class="mt-1 mb-2">

    <a class="title text-truncate mb-0" href="{{ post.get_absolute_url }}">{{post.title}}</a>

    {% if post.content %}
      <div class="content content-preview text-white mt-1 mb-2">
        {{ post.rendered_content|safe }}
      </div>
    {% endif %}

    <div class="tags-wrapper mt-3 d-flex flex-wrap gap-2">
      {% for tag in post.tags.all|dictsort:"name" %}
        <a href="{{ tag.get_absolute_url }}" class="tag-badge">&nbsp;{{ tag.name }}&nbsp;</a>
      {% endfor %}
    </div>

    <div class="mt-2 d-flex justify-content-between align-items-center">

      {% url 'posts:toggle_like_post' post.pk post.slug as toggle_like_url %}

      {% with liked_object=post user_has_liked=post.user_has_liked likes_count=post.likes_count toggle_like_url=toggle_like_url %}
        {% include 'posts/likes/_like-button.html' %}
      {% endwith %}

      <div class="d-flex justify-content-end">
        <a href="{{ post.get_absolute_url }}#comments-wrapper" class="more-link me-3">
          <span>
            Комментарии:
          </span>
          <span id="comments_count" class="text-warning">
            {{ post.comments_count }}
          </span>
        </a>

        <a href="{{ post.get_absolute_url }}" class="more-link">
          Подробнее
        </a>
      </div>

    </div>

  </div>
</div>

studyoverflow/posts/templates/posts/post_create.html
{% extends 'posts/post_form_base.html' %}
{% load static %}


{# Шаблон страницы создания поста на основе базовой формы #}

{% block title %}
  <title>Создание поста</title>
{% endblock %}


{% block heading %}
  <h2>Создать новый пост</h2>
{% endblock %}


{% block button_confirm %}
  Отправить
{% endblock %}


{% block button_cancel %}
  <a href="{% url 'home' %}"
     class="btn btn-outline-light">
    Отмена
  </a>
{% endblock %}

studyoverflow/posts/templates/posts/post_detail.html
{% extends 'navigation/base.html' %}
{% load static %}
{% load posts_tags %}
{% load users_tags %}


{# Шаблон страницы детального представления поста #}

{% block title %}
    <title>Пост</title>
{% endblock %}


{% block extra_css %}
  {# Подключение CSS-темы для подсветки синтаксиса кода #}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github-dark.min.css">

  <link type="text/css" rel="stylesheet" href="{% static 'posts/css/post_base.css' %}">

  <link type="text/css" rel="stylesheet" href="{% static 'posts/css/post_detail.css' %}">

  <link type="text/css" rel="stylesheet" href="{% static 'posts/css/comment_card.css' %}">

  <link type="text/css" rel="stylesheet" href="{% static 'posts/css/comment_sort.css' %}">

  <link type="text/css" rel="stylesheet" href="{% static 'posts/css/like_button.css' %}">

  <link type="text/css" rel="stylesheet" href="{% static 'users/css/avatar_modal.css' %}">
{% endblock %}


{% block content %}

  <main class="container px-4 px-lg-0 my-4" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    <div class="row mt-4 mx-0">

      <div class="card text-white rounded shadow-sm px-4 mb-4">
        <div class="card-body px-0 pb-2">

        <div class="d-flex align-items-center mb-2">

          <img id="avatar"
               src="{{ post.author.avatar_small_size2_url }}"
               alt="{{ post.author.username }}"
               class="rounded-circle"
               style="cursor:pointer;"

               hx-get="{% url 'users:avatar_preview' post.author.username %}"
               hx-target="#modal-image-container"
               hx-swap="innerHTML"

               hx-indicator="#modal-loading-indicator"
               hx-on:htmx:before-request="openModal()">

          <div>
            <a id="username" href="{% url 'users:profile' post.author.username %}" class="author-name d-inline-block mb-1">
              {{ post.author.username }} {% user_role_badge post.author %}
            </a>

            <div id="time_create-time_update" class="text-secondary">
              Опубликовано: {{ post.time_create|date:"d.m.Y г. H:i" }}
              {% if post.is_edited %}
                &nbsp;|&nbsp; Изменено: {{ post.time_update|date:"d.m.Y г. H:i" }}
              {% endif %}
            </div>
          </div>

        </div>

          <hr class="mt-1 mb-2">

          <span class="title text-truncate mb-0">{{post.title}}</span>

          {% if post.content %}
            <div class="content text-white mt-2 mb-2">
              {{ post.rendered_content|safe }}
            </div>
          {% endif %}

          <div class="tags-wrapper mt-4 d-flex flex-wrap gap-2">
            {% for tag in post.tags.all|dictsort:"name" %}
              <a href="{{ tag.get_absolute_url }}" class="tag-badge">&nbsp;{{ tag.name }}&nbsp;</a>
            {% endfor %}
          </div>

          <div class="d-flex justify-content-between align-items-center mt-2 mb-1">

            {% url 'posts:toggle_like_post' post.pk post.slug as toggle_like_url %}

            {% with liked_object=post user_has_liked=post.user_has_liked likes_count=post.likes_count toggle_like_url=toggle_like_url %}
              {% include 'posts/likes/_like-button.html' %}
            {% endwith %}

              <div class="d-flex justify-content-end">
                {% if post.author == user or perms.posts.moderate_post %}
                  <a href="{% url 'posts:edit' post.pk post.slug %}" class="btn btn-outline-warning btn-sm me-3">
                    Редактировать
                  </a>

                  <button type="button"
                          class="btn btn-outline-danger btn-sm me-3"
                          data-bs-toggle="modal"
                          data-bs-target="#deletePostModal">
                      Удалить
                  </button>

                  {% url 'posts:delete' post.pk post.slug as post_delete_url %}

                  {% include 'navigation/_modal_delete.html' with modal_id="deletePostModal" form_action=post_delete_url title="Подтверждение удаления поста" message="Вы уверены, что хотите удалить этот пост?" %}

                {% endif %}

                <button id="show-comment-form" type="button" class="btn btn-outline-light btn-sm">
                  Комментировать
                </button>
              </div>

          </div>

        </div>
      </div>

      {# Форма комментария поста #}
      <div id="comment-form-container"
           style="display: none;" class="w-100 mb-4 px-0">
        {% include 'posts/comments/_comment_root_form.html' %}
      </div>

      {# Загрузка комментариев поста#}
      <div id="comments-wrapper"
           class="position-relative"
           hx-get="{% url 'posts:comment_list' post.pk post.slug %}"
           hx-trigger="load, commentsUpdated from:body"
           hx-swap="innerHTML"
           hx-indicator="#loading-indicator">

        {% include 'posts/comments/comment_list.html' %}

        {# Индикатор загрузки #}
        <div id="loading-indicator"
             class="d-flex flex-column justify-content-center align-items-center py-2"
             style="display: none;">
          <div class="spinner-border text-light mb-2" role="status"></div>
          <span class="text-light">Загрузка комментариев...</span>
        </div>

      </div>

    </div>
  </main>

  {% include 'users/_avatar_modal.html' %}

{% endblock %}


{% block extra_js %}
  {# Подключение JS-скрипта highlight.js для подсветки синтаксиса кода #}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>

  <script src="{% static 'posts/js/post_detail.js' %}"></script>

  <script src="https://unpkg.com/htmx.org@2.0.7"></script>

  {# Запуск highlight.js #}
  <script src="{% static 'posts/js/highlight_run.js' %}"></script>

  <script src="{% static 'users/js/avatar_modal.js' %}"></script>

  <script src="{% static 'posts/js/comments_detail.js' %}"></script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
{% endblock %}

studyoverflow/posts/templates/posts/post_edit.html
{% extends 'posts/post_form_base.html' %}
{% load static %}


{# Шаблон страницы редактирования поста #}

{% block title %}
  <title>Редактирование поста</title>
{% endblock %}


{% block heading %}
  <h2>Редактировать пост</h2>
{% endblock %}


{% block button_confirm %}
  Редактировать
{% endblock %}


{% block button_cancel %}
  <a href="{{ post.get_absolute_url }}"
     class="btn btn-outline-light">
    Отмена
  </a>
{% endblock %}

studyoverflow/posts/templates/posts/users.html
{% extends 'base/base.html' %}


{% block title %}
    <title>Пользователи</title>
{% endblock %}

{% block content %}
{% endblock %}