studyoverflow/notifications/urls.py
from django.urls import path

from . import views


app_name = "notifications"


urlpatterns = [
    path("", views.NotificationTemplateView.as_view(), name="base"),
    path("list/", views.NotificationListView.as_view(), name="list"),
    path("mark-read/<int:pk>/", views.NotificationMarkReadView.as_view(), name="mark_read"),
    path("mark-read-all/", views.NotificationMarkAllReadView.as_view(), name="mark_all_read"),
    path("delete/<int:pk>/", views.NotificationDeleteView.as_view(), name="delete"),
    path("delete-all/", views.NotificationDeleteAllView.as_view(), name="delete_all"),
]

studyoverflow/posts/urls.py
from django.urls import path
from posts import views


app_name = "posts"


urlpatterns = [
    path("", views.PostListView.as_view(), name="list"),
    path("create/", views.PostCreateView.as_view(), name="create"),
    path("<int:pk>/<slug:slug>/", views.PostDetailView.as_view(), name="detail"),
    path("edit/<int:pk>/<slug:slug>/", views.PostUpdateView.as_view(), name="edit"),
    path("delete/<int:pk>/<slug:slug>/", views.PostDeleteView.as_view(), name="delete"),
    path(
        "<int:post_pk>/<slug:post_slug>/comments/",
        views.CommentListView.as_view(),
        name="comment_list",
    ),
    path(
        "<int:post_pk>/<slug:post_slug>/comments/root/create/",
        views.CommentRootCreateView.as_view(),
        name="comment_root_create",
    ),
    path(
        "<int:post_pk>/<slug:post_slug>/comments/child/create/",
        views.CommentChildCreateView.as_view(),
        name="comment_child_create",
    ),
    path(
        "<int:post_pk>/<slug:post_slug>/comments/<int:comment_pk>/update/",
        views.CommentUpdateView.as_view(),
        name="comment_update",
    ),
    path(
        "<int:post_pk>/<slug:post_slug>/comments/<int:comment_pk>/delete/",
        views.CommentDeleteView.as_view(),
        name="comment_delete",
    ),
    path(
        "<int:post_pk>/<slug:post_slug>/likes/",
        views.ToggleLikePostView.as_view(),
        name="toggle_like_post",
    ),
    path(
        "<int:post_pk>/<slug:post_slug>/comments/<int:comment_pk>/likes/",
        views.ToggleLikeCommentView.as_view(),
        name="toggle_like_comment",
    ),
]

studyoverflow/users/urls.py
from django.urls import path
from users import views


app_name = "users"


urlpatterns = [
    path("", views.UsersListView.as_view(), name="list"),
    path("list-htmx/", views.UsersListHTMXView.as_view(), name="list_htmx"),
    path("register/", views.UserRegisterView.as_view(), name="register"),
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("logout/", views.UserLogoutView.as_view(), name="logout"),
    path("delete/", views.UserDeleteView.as_view(), name="delete"),
    path("profile/me/", views.UserProfileUpdateView.as_view(), name="my_profile"),
    path("profile/<slug:username>/", views.AuthorProfileView.as_view(), name="profile"),
    path("avatar/<slug:username>/preview/", views.avatar_preview, name="avatar_preview"),
    path("password-change/", views.UserPasswordChangeView.as_view(), name="password_change"),
    path("password-reset/", views.UserPasswordResetView.as_view(), name="password_reset"),
    path(
        "password-reset/done/",
        views.UserPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password-reset/confirm/<uidb64>/<token>/",
        views.UserPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        views.UserPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("block/<int:user_id>/", views.block_user, name="block_user"),
    path("unblock/<int:user_id>/", views.unblock_user, name="unblock_user"),
]

studyoverflow/notifications/models.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models

from studyoverflow import settings


class NotificationType(models.TextChoices):
    """
    Перечисление типов уведомлений.
    """

    LIKE_POST = "like_post", "Лайк поста"
    LIKE_COMMENT = "like_comment", "Лайк комментария"
    POST = "post_created", "Пост создан"
    COMMENT = "comment_post", "Комментарий к посту"
    REPLY = "reply_comment", "Ответ на комментарий"
    REGISTER = "user_register", "Регистрация пользователя"


class Notification(models.Model):
    """
    Модель уведомлений на различные события.

    Поля:
    - user (ForeignKey): Получатель уведомления.
    - actor (ForeignKey): Инициатор события (тот, кто совершил действие).
    - notification_type (CharField): Тип уведомления (LIKE_POST, COMMENT и т.д.).
    - content_type (ForeignKey): Ссылка на модель связанного объекта (Post, Comment и т.д.).
    - object_id (PositiveIntegerField): ID записи в связанной модели.
    - content_object (GenericForeignKey): Экземпляр связанного объекта.
    - message (CharField): Текстовое сообщение уведомления.
    - is_read (BooleanField): Флаг прочтения уведомления пользователем.
    - time_create (DateTimeField): Дата и время автоматической генерации записи.
    """

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="notifications",
        verbose_name="Пользователь",
        help_text="Пользователь, которому адресовано уведомление",
    )
    actor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="actor_notifications",
        verbose_name="Инициатор",
        help_text="Пользователь, который совершил действие",
    )

    notification_type = models.CharField(
        max_length=50,
        choices=NotificationType.choices,
        verbose_name="Тип",
        help_text="Тип уведомления",
    )
    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name="Тип связанного объекта",
    )
    object_id = models.PositiveIntegerField(
        null=True, blank=True, verbose_name="ID связанного объекта"
    )
    content_object = GenericForeignKey("content_type", "object_id")

    message = models.CharField(
        max_length=255,
        blank=True,
        verbose_name="Сообщение",
        help_text="Текстовое описание уведомления",
    )

    is_read = models.BooleanField(default=False, verbose_name="Статус")
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")

    class Meta:
        verbose_name = "Уведомление"
        verbose_name_plural = "Уведомления"
        ordering = ["-time_create"]
        indexes = [
            # Индекс для непрочитанных уведомлений пользователя:
            #   Notification.objects.filter(user=user, is_read=False)
            #       WHERE user_id = ? AND is_read = False
            models.Index(fields=["user", "is_read"]),
            # Индекс для получения всех уведомлений пользователя с сортировкой по дате создания:
            #   Notification.objects.filter(user=user).order_by('-time_create')
            #       WHERE user_id = ?
            #       ORDER BY time_create DESC
            models.Index(fields=["user", "-time_create"]),
        ]

    def __str__(self):
        """Возвращает строковое представление объекта."""
        return f"{self.user} <- {self.actor}: {self.get_notification_type_display()}"

studyoverflow/notifications/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.prefetch import GenericPrefetch
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404
from django.views import View
from django.views.generic import ListView, TemplateView
from notifications.models import Notification
from notifications.tasks import send_channel_notify_event
from posts.models import Comment, Like, Post
from posts.views.mixins import LoginRequiredRedirectHTMXMixin


class NotificationTemplateView(LoginRequiredMixin, TemplateView):
    """Отображает базовый шаблон страницы уведомлений."""

    template_name = "notifications/notification_base.html"


class NotificationListView(LoginRequiredRedirectHTMXMixin, ListView):
    """
    Возвращает список уведомлений текущего пользователя.
    """

    model = Notification
    template_name = "notifications/_notification_list.html"
    context_object_name = "notification_list"

    def get_queryset(self):
        queryset = super().get_queryset()

        queryset = (
            queryset.filter(user=self.request.user)
            .select_related("user", "actor", "content_type")
            .prefetch_related(
                GenericPrefetch(
                    "content_object",
                    [
                        Post.objects.all(),
                        Comment.objects.select_related("post"),
                        Like.objects.prefetch_related(
                            GenericPrefetch(
                                "content_object",
                                [
                                    Post.objects.all(),
                                    Comment.objects.select_related("post"),
                                ],
                            )
                        ),
                    ],
                )
            )
        )

        return queryset


class NotificationMarkReadView(LoginRequiredRedirectHTMXMixin, View):
    """
    Помечает уведомление как прочитанное, если оно принадлежит текущему пользователю.
    """

    def post(self, request, *args, **kwargs):
        notification = get_object_or_404(Notification, pk=kwargs["pk"])

        if notification.user != request.user:
            return HttpResponseForbidden("Not allowed")

        if not notification.is_read:
            notification.is_read = True
            notification.save(update_fields=["is_read"])

        return HttpResponse()


class NotificationMarkAllReadView(LoginRequiredRedirectHTMXMixin, View):
    """
    Помечает все уведомления текущего пользователя прочитанными и создает
    Celery задачу для обновления счетчика непрочитанных уведомлений
    через Channels WebSocket.
    """

    def post(self, request, *args, **kwargs):
        Notification.objects.filter(user=request.user, is_read=False).update(is_read=True)

        send_channel_notify_event.delay(user_id=request.user.pk, update_list=False)

        return HttpResponse()


class NotificationDeleteView(LoginRequiredRedirectHTMXMixin, View):
    """
    Удаляет уведомление текущего пользователя.
    """

    def post(self, request, *args, **kwargs):
        notification = get_object_or_404(Notification, pk=kwargs["pk"])

        if notification.user != request.user:
            return HttpResponseForbidden("Not allowed")

        notification.delete()

        return HttpResponse()


class NotificationDeleteAllView(LoginRequiredRedirectHTMXMixin, View):
    """
    Удаляет все уведомления текущего пользователя.
    """

    def post(self, request, *args, **kwargs):
        notifications = Notification.objects.filter(user=request.user)

        if not notifications.exists():
            return HttpResponse()

        notifications.delete()

        return HttpResponse()

studyoverflow/notifications/templates/notifications/_notification_card.html
{% load users_tags %}


{# Шаблон карточки уведомления #}
<div id="notification-card-{{ notification.id }}" class="card text-white rounded shadow-sm px-4 {% if not notification.is_read %}border border-warning{% endif %}">
  <div class="card-body px-0 pb-2">

    {# Автор и время #}
    <div class="d-flex align-items-center mb-2">
      <img id="avatar-comment"
           src="{{ notification.actor.avatar_small_size1_url }}"
           alt="{{ notification.actor.username }}"
           class="rounded-circle"
           style="cursor:pointer;"

           hx-get="{% url 'users:avatar_preview' notification.actor.username %}"
           hx-target="#modal-image-container"
           hx-swap="innerHTML"

           hx-indicator="#modal-loading-indicator"
           hx-on:htmx:before-request="openModal()">

      <div class="image-modal-wrapper"></div>

      <div>
        <div class="d-flex align-items-center mb-1">
          <a href="{% url 'users:profile' notification.actor.username %}" class="username-comment author-name me-1">{{ notification.actor.username }} {% user_role_badge notification.actor %}</a>
        </div>

        <div id="time_create-time_update-comment" class="text-secondary">
          Создано: {{ notification.time_create|date:"d.m.Y г. H:i" }}
        </div>
      </div>
    </div>

    <hr class="mt-1 mb-2">

    {# Блок содержимого комментария #}
    <div id="notification-content-{{ notification.id }}" class="text-start text-white mt-1 px-1">
      {{ notification.message }}
      {% if notification.content_object %}
        <a href="{{ notification.content_object.get_absolute_url }}" class="more-link">
          Посмотреть
        </a>
      {% endif %}
    </div>

    <div class="d-flex justify-content-end align-items-center mt-2">

      <div class="d-flex mb-1">
          <button type="button"
                  class="btn btn-sm me-3 mark-read-btn
                         {% if notification.is_read %}
                             btn-outline-warning disabled
                         {% else %}
                             btn-outline-warning
                         {% endif %}"
                  data-notification-id="{{ notification.id }}"
                  {% if not notification.is_read %}
                      hx-post="{% url 'notifications:mark_read' notification.id %}"
                      hx-trigger="click"
                      hx-swap="none"
                  {% endif %}>
              {% if notification.is_read %}
                  Прочитано
              {% else %}
                  Отметить прочитанным
              {% endif %}
          </button>

          <button type="button"
                  class="btn btn-outline-danger btn-sm delete-notification-btn"
                  data-notification-id="{{ notification.id }}"
                  hx-post="{% url 'notifications:delete' notification.id %}"
                  hx-trigger="click"
                  hx-target="#notification-wrapper-{{ notification.id }}"
                  hx-swap="delete">
              Удалить
          </button>

      </div>

  </div>

  </div>
</div>

studyoverflow/notifications/templates/notifications/_notification_list.html
{# Управление списком уведомлений и контейнер карточек уведомлений #}
<div class="d-flex justify-content-center gap-5 mt-3 mb-4">
  <button id="mark-all-read-btn"
          class="btn btn-warning"
          hx-post="{% url 'notifications:mark_all_read' %}"
          hx-trigger="click"
          hx-swap="none">
      Отметить все прочитанными
  </button>

  <button class="btn btn-outline-light px-3"
          hx-post="{% url 'notifications:delete_all' %}"
          hx-trigger="click"
          hx-swap="delete"
          hx-target="#notification-container">
      Удалить все оповещения
  </button>
</div>

{% if notification_list %}
  <div id="notification-container" class="d-flex flex-column px-0 col-md-8 mx-auto" style="gap: 1.5rem;">
    {% for notification in notification_list %}

      <div id="notification-wrapper-{{ notification.id }}">
        {% include 'notifications/_notification_card.html' %}
      </div>

    {% endfor %}
  </div>
{% endif %}

studyoverflow/notifications/templates/notifications/notification_base.html
{% extends 'navigation/base.html' %}
{% load static %}


{# Основной шаблон страницы уведомлений #}

{% block title %}
    <title>Уведомления</title>
{% endblock %}


{% block extra_css %}
  <link type="text/css" rel="stylesheet" href="{% static 'users/css/avatar_modal.css' %}">
  <link type="text/css" rel="stylesheet" href="{% static 'posts/css/comment_card.css' %}">
  <link type="text/css" rel="stylesheet" href="{% static 'posts/css/post_base.css' %}">
  <link type="text/css" rel="stylesheet" href="{% static 'notifications/css/notification_list.css' %}">
{% endblock %}


{% block content %}
  <div class="container py-5" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>

    {# Новые уведомления #}
    <div class="text-center">

      <h3 class="text-white">
        Оповещения
      </h3>

      <div id="notifications-list"
           hx-get="/notifications/list/"
           hx-trigger="load"
           hx-target="#notifications-list"
           hx-swap="innerHTML">

        {# Индикатор загрузки #}
        <div id="loading-indicator" class="htmx-indicator d-flex flex-column justify-content-center align-items-center py-2">
          <div class="spinner-border text-light mb-2" role="status"></div>
          <span class="text-light">Загрузка оповещений...</span>
        </div>

      </div>

      <div id="container-no-notifications" style="display: none">
        <h5 class="text-secondary">Нет оповещений</h5>
      </div>

    </div>

  </div>

  {% include 'users/_avatar_modal.html' %}

{% endblock %}


{% block extra_js %}
  <script src="{% static 'users/js/avatar_modal.js' %}"></script>

  <script src="{% static 'notifications/js/notification_list.js' %}"></script>

  <script src="https://unpkg.com/htmx.org@2.0.7"></script>
{% endblock %}